apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        service: {{ .Chart.Name }}
    spec:
{{- /*
See chart value file for details of the logic used to generate this setting value below.!!!
*/}}
{{- $imagePullSecret := (ne (.Values.image.imagePullSecret | typeOf) "<nil>") | ternary .Values.image.imagePullSecret ( (ne (.Values.global.image.imagePullSecret | typeOf) "<nil>") | ternary .Values.global.image.imagePullSecret .Values.defaultImage.imagePullSecret ) -}}
      {{- if ne ($imagePullSecret | toString) "false" }}
      imagePullSecrets:
      - name: {{ $imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository | default .Values.global.image.repository | default .Values.defaultImage.repository }}/{{ .Values.image.name | default .Chart.Name }}:{{ .Values.image.tag | default .Values.global.image.tag | default .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy | default .Values.defaultImage.pullPolicy }}
        command: [
            "node",
            "/usr/src/app/component/dist/index.js",
            "--listenPort", "80",
            "--dbHost", "session-db",
            "--dbPort", "5432",
            "--cookieJson", "/etc/gateway-config/cookie.json",
            "--externalUrl", {{ .Values.global.externalUrl | quote }},
            "--authPluginRedirectUrl", {{ .Values.authPluginRedirectUrl | default .Values.global.authPluginRedirectUrl | quote }},
            "--authApiUrl", "http://authorization-api/v0",
            "--authPluginConfigJson", "/etc/{{ .Chart.Name }}-config/authPluginConfig.json"
        ]
        volumeMounts:
          - name: gateway-config
            mountPath: /etc/gateway-config
          - name: "{{ .Chart.Name }}-config"
            mountPath: "/etc/{{ .Chart.Name }}-config"
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId | default .Values.defaultAdminUserId }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: session-secret
{{- if .Values.global.noDbAuth }}
        - name: PGUSER
          value: client
{{- else }}
        - name: PGUSER
          value: client
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-passwords
              key: session-db-client
{{- end }}
      # --- load cookie setting from gateway-config
      volumes:
        - name: gateway-config
          configMap:
            name: gateway-config
        - name: "{{ .Chart.Name }}-config"
          configMap:
            name: "{{ .Chart.Name }}-config"
